### ISSUE TITLE
加载bluecrawl-1.0.0.js失败

### ISSUE THREAD

**Issue by hustwyk** [r0ysue/AndroidSecurityStudy#1]
![image](https://user-images.githubusercontent.com/6143567/75642921-2f713280-5c78-11ea-95bb-4f71ba374f23.png)
脚本195行是改变控制台输出颜色，node直接输出都没问题，frida脚本的console.log里输出就会failed，请问该怎么破

**Comment by r0ysue** [comment]
咱们是学习如何使用frida，不是学加颜色，也不是替frida修bug。这个bug可以去frida的github去提。
