### ISSUE TITLE
Android7.1.2 编译Fart有个错误art_method.cc:137

### ISSUE THREAD

**Issue by ohyeah521** [r0ysue/AndroidSecurityStudy#4]
art/runtime/art_method.cc:137:3: error: expected function body after function declarator
         SHARED_LOCKS_REQUIRED(Locks::mutator_lock_) {
         ^
1 error generated.
[  2% 155/5479] target Java: core-all (out/target/common/obj/JAVA_LIBRARIES/core-all_intermediates/classes)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
ninja: build stopped: subcommand failed.
make: *** [ninja_wrapper] Error 1

**Comment by ohyeah521** [comment]
网盘中的aosp_pure_source_code是否已经包含了fart源码，如果是我去下载一份对比一下

**Comment by r0ysue** [comment]
pure 的意思是“纯”，纯aosp源码 。

**Comment by ohyeah521** [comment]
大佬，这个错误是什么原因导致的，有什么解决办法吗，我是直接把寒冰大佬开源的6.0的源码移植过来的，不知道您在编译的时候有没有遇到类似的问题
