### ISSUE TITLE
traceMethod如何实现

### ISSUE THREAD

**Issue by crazyn2** [r0ysue/AndroidSecurityStudy#6]
Frida Java Hook 详解（安卓9）：代码及示例（下）1.5 Java层拦截类的所有方法中traceMethod是如何实现传入参数函数完整路径进行注入的啊？
本人经过尝试无法实现，只能以类为单位对所有方法进行拦截，请问博主是如何直接实现的

**Comment by r0ysue** [comment]
https://github.com/r0ysue/AndroidSecurityStudy/blob/master/FRIDA/B02/README.md
