### ISSUE TITLE
求介绍如何定位到合适的Hook点

### ISSUE THREAD

**Issue by cfrchj** [r0ysue/AndroidSecurityStudy#8]
大佬的教程介绍了Hook Java层、SO层各类函数的方法，但是如何找到合适的Hook点呢？
迫切希望大佬能以案例介绍几种定位到Hook点方法或者套路，本人愿意给大佬打下手。

**Comment by r0ysue** [comment]
如何定位是一套完整的逆向流程，太大了。
会有文章进行介绍的。
