### ISSUE TITLE
pixel 4 kernelSU 开了Shamiko模块 已经移动到系统目录的Charles证书丢失

### ISSUE THREAD

**Issue by wangyuan0217** [r0ysue/AndroidSecurityStudy#9]
经反复测试；kernelSU(已安装MoveCe1.9模块)里安装Shamiko
-  不开启的时候
  安装Charles的pem，然后重启；是会被自动移动系统目录的；正常；
- 开启的时候
  安装Charles的pem，然后重启，系统目录和用户目录都找不到Charles证书，丢失；
  或者在不开启Shamiko的时候安装证书并重启正常被移动到系统目录的时候，在开启Shamiko在重启，证书也会丢失；

那要怎么搞啊，Shamiko不是要用来隐藏么；不然momo hunter 都会发现的

**Comment by fengyinws** [comment]
Hello,Your email has been received and I will process it as soon as possible!Best wishes!

**Comment by wangyuan0217** [comment]
机器人吗

**Comment by r0ysue** [comment]
好像确实跟shamiko是冲突的。。

**Comment by fengyinws** [comment]
Hello,Your email has been received and I will process it as soon as possible!Best wishes!
